#ifndef QTGOOGLEFEEDS_GLOBAL_H
#define QTGOOGLEFEEDS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTGOOGLEFEEDS_LIBRARY)
#  define QTGOOGLEFEEDSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTGOOGLEFEEDSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTGOOGLEFEEDS_GLOBAL_H
